Add rustdoc deployment to gh-pages
NordSecurity/libtelio pull request #488
Opened 2024-04-17 08:40 UTC by ThrasherLT

Rust doc will be build and uploaded to libtelio GitHub Pages website by GitHub Actions when manually triggered

### Problem
There's no convenient way to transfer libtelio documentation to app teams

### Solution
Rust Doc are now built and the resulting artifact is uploaded to GitHub pages for the app teams to easily access

2024-04-17 12:09 UTC, gytsto commented
I think you forgot to add your jobs to `.github/workflows/ci.yml`, because I don't see where are they being triggered. Or should it be disabled for now?

2024-04-17 12:34 UTC, gytsto commented
> > I think you forgot to add your jobs to `.github/workflows/ci.yml`, because I don't see where are they being triggered. Or should it be disabled for now?
> 
> @gytsto It's supposed to be triggered manually on CI. I've described the triggering part in more detail in the PR description.

Oh, I somehow missed the note before.

2024-04-17 12:34 UTC, gytsto approved these changes
+1

2024-04-17 18:20 UTC, packgron commented on .github/workflows/gh-pages.yml
> +        toolchain: nightly
Lock to some specific version of nightly

2024-04-17 18:23 UTC, packgron requested changes
Let's change Cargo.toml version with this commit

2024-04-18 08:51 UTC, packgron commented on .github/workflows/gh-pages.yml
> +        toolchain: nightly-2023-06-01
use a newer one, we are no longer locked to old version, since we updated rust version.

2024-04-18 10:38 UTC, packgron approved these changes
+1.0

2024-04-18 11:41 UTC, merged