Update README.md: Add gcc check and ca-certificates installation (in Dockerfile)
NordSecurity/libtelio pull request #558
Opened 2024-05-20 14:21 UTC by olekoliinyk

1. Add to README.md check to verify if gcc (required for libtelio build) was installed. 
2. Add ca-certificates package (in order to connect to Derb server) installation for Docker container in README.md

### Problem
1. During build of libetlio on linux VM there was following error:
` error: linking with `/home/{username}/libtelio/linkers/d-x86_64-linux-gnu-gcc` failed: exit status: 127`
2. Peer in docker container was not able to connect to DERB:
`2024-05-17T08:55:07.250137Z  WARN telio_relay::derp: 284: (DerpRelay) Failed to connect: I/O Error: invalid peer certificate: UnknownIssuer`

### Solution
1. For linux VM add check to verify if gcc (GNU Compiler Collection) is installed
2. Add `ca-certificates` to Dockerfile

2024-05-20 14:50 UTC, packgron approved these changes

2024-05-20 14:52 UTC, packgron requested changes
Commit message a bit to long, should be split as written here:
https://github.com/NordSecurity/libtelio/blob/main/docs/git_commit_messages_requirements.md

2024-05-20 15:34 UTC, gytsto approved these changes
+1

2024-05-21 10:22 UTC, packgron approved these changes
+1.0

2024-05-21 10:26 UTC, merged