Bump build-linux-rust to 1.77.2:v0.0.4
NordSecurity/libtelio pull request #657
Opened 2024-07-02 15:18 UTC by tomaszklak

### Problem
Old version was build only for amd64.

### Solution
This version is the first built for both arm64 and amd64.

2024-07-02 15:22 UTC, tomaszklak commented on .github/workflows/gitlab.yml
> +          triggered-ref: LLT-5248-bump-build-linux-rust
❗REMINDER TO EDIT BEFORE MERGE❗

2024-07-02 15:22 UTC, tomaszklak commented on .gitlab-ci.yml
> +    branch: LLT-5248-bump-build-linux-rust
❗REMINDER TO EDIT BEFORE MERGE❗

2024-07-03 09:01 UTC, Jauler requested changes
:) triggered-ref` needs to be updated.

2024-07-03 11:31 UTC, tomaszklak commented
> :) `triggered-ref` needs to be updated (:

Done ;)

2024-07-03 11:32 UTC, Jauler approved these changes
+2.0

2024-07-03 14:14 UTC, merged